#!/bin/bash
# Test File
echo "berge" > testresults
(time ./a.out -a ../../../vc-data/Ashay-Dharwadker/berge-n60-k40.txt) &>> testresults

echo >>testresults
echo "bipartite">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/bipartite-n6-k3.txt) &>> testresults

echo >>testresults
echo "bondy-murty-n7-k4">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/bondy-murty-n7-k4.txt) &>>testresults

echo >>testresults
echo "bondy-murty-n11-k7">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/bondy-murty-n11-k7.txt) &>>testresults

echo >>testresults
echo "bondy-murty-n14-k7">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/bondy-murty-n14-k7.txt) &>>testresults

echo >>testresults
echo "cube-n8-k4">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/cube-n8-k4.txt) &>>testresults

echo >>testresults
echo "dodecahedron-n20-k12">>testresults
(time ./a.out -a ../../../vc-data/Ashay-Dharwadker/dodecahedron-n20-k12.txt) &>>testresults

echo >>testresults
echo "folkman-n20-k10">>testresults
(time ./a.out -a ../../../vc-data/Ashay-Dharwadker/folkman-n20-k10.txt) &>>testresults

echo >>testresults
echo "grotzsch-n11-k6">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/grotzsch-n11-k6.txt) &>>testresults

echo >>testresults
echo "herschel-n11-k5">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/herschel-n11-k5.txt) &>>testresults

echo >>testresults
echo "icosahedron-n12-k9">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/icosahedron-n12-k9.txt) &>>testresults

echo >>testresults
echo "octahedron-n6-k4">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/octahedron-n6-k4.txt) &>>testresults

echo >>testresults
echo "petersen-n10-k6">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/petersen-n10-k6.txt) &>>testresults

echo >>testresults
echo "ransey-n17-k-14">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/ransey-n17-k-14.txt) &>>testresults

echo >>testresults
echo "tetrahedron-n4-k3">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/tetrahedron-n4-k3.txt) &>>testresults

echo >>testresults
echo "thomassen-n34-k20">>testresults
(time ./a.out -a ../../../vc-data/Ashay-Dharwadker/thomassen-n34-k20.txt) &>>testresults

echo >>testresults
echo "tutte-coxeter-n30-k15">>testresults
(time ./a.out -a ../../../vc-data/Ashay-Dharwadker/tutte-coxeter-n30-k15.txt) &>>testresults

echo >>testresults
echo "wheel-n8-k5">>testresults
(time ./a.out -l ../../../vc-data/Ashay-Dharwadker/wheel-n8-k5.txt) &>>testresults